### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by AlexandrovOne** [parkerjon/jpVolumeLayers#1]
### "There were errors while matching the new node to its definition"
Seems like Houdini can't see new VOP `VolumeLayer` structure. (?)

I'm using Houdini 19.5.569, Windows OS and the latest release of this plugin - `1.3.3`. 
And these are the steps I used to install your plugin:

1. I put the whole `volumelayers` folder into the `$HOME/houdini19.5/packages` directory.
2. My `volumelayers.json` also located in the `$HOME/houdini19.5/packages` directory, and looks like this:
```
{
    "hpath": "$VEX_VOLUMELAYERS",
    "load_package_once": true,
    "enable": "houdini_version >= '17.5' and houdini_version < '20.1'",
    "version": "1.0.0",
    "env": [
        {
            "VEX_VOLUMELAYERS": "$HOUDINI_PACKAGE_PATH/volumelayers/"
        }
    ]
}
```

Houdini sees the nodes, but when I place these nodes:

1. `Volume Layer Add Quantity VOP`
2. `Volume Layer Adjust Multiscatter VOP`
3. `Volume Layer Compute Lighting VOP`
4. `Volume Layer Shader VOP`
5. `Volume Layer Space Transform VOP`
6. `Volume Layer To Shading Layer VOP`

Houdini gives me pop-up error: 
![image_2023-11-12_20-15-31](https://github.com/parkerjon/jpVolumeLayers/assets/150603421/35d589cd-fb52-4846-9646-2069b5602300)
**There were errors while matching the new node to its definition**

Maybe I am doing something wrong?

**Comment by parkerjon** [comment]
Hi @AlexandrovOne ,

Thanks, I confirmed this bug locally.  The release tag was not up-to-date with the repo and contained some issues that had since been fixed in the main branch (but not tagged).

I've created a new tag, v1.3.5 which should fix these issues.  Please download the new release and see if it fixes the node issues.  

I've also modified `volumelayers.json` to match your method above, since it's actually a simpler way to install the package.  Thanks for reminding me of that!

**Comment by AlexandrovOne** [comment]
Huge thanks for you, @parkerjon! It's working! ⚙️ 

Nodes are completely functional now and do not create any errors 😄 

Installation now works really well. Literally 2 klicks.
And I'm so glad I was able to help you too 🔥

I can't wait to play around and create something cool!
Incredibly many thanks to you, @parkerjon, for this amazing toolset! ❤️⭐ 
I've always wanted something like this for Houdini! Incredible!

![image_2023-11-13_22-25-33](https://github.com/parkerjon/jpVolumeLayers/assets/150603421/508cdc81-a342-44a6-bc58-feee9fa56cdb)

**Comment by parkerjon** [comment]
Excellent!
